/*
 * Copyright 2018 dika.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package com.carRental.activity;

import com.carRental.activity.main.PengembalianContainerImpl;
import com.carRental.activity.main.PengembalianContainer;
import com.carRental.activity.main.SewaContainer;
import com.carRental.activity.main.SewaContainerImpl;
import com.dika.res.SmallIconRes;
import com.dika.view.component.Frame;

import javax.swing.*;

/**
 *
 * @author dika
 */
public class MainViewImpl extends Frame implements MainView{

    /**
     * Creates new form MainViewImpl
     */
    public MainViewImpl() {
        initComponents();
        SmallIconRes res = SmallIconRes.INSTANCE;
        programMenu.setIcon(res.getAppsIcon());
        dataManagerMenu.setIcon(res.getOfficeIcon());
        aboutMenu.setIcon(res.getInfoIcon());
        
        changeUsernameMenu.setIcon(res.getUpdateIcon());
        changePasswordMenu.setIcon(res.getUpdateIcon());
        logoutMenu.setIcon(res.getLogoutIcon());
        exitMenu.setIcon(res.getExitIcon());

        mdTransaksiMenu.setIcon(res.getDotIcon());
        mdMerkMenu.setIcon(res.getDotIcon());
        mdKaryawanMenu.setIcon(res.getDotIcon());
        mdUserMenu.setIcon(res.getDotIcon());
        mdPelangganMenu.setIcon(res.getDotIcon());
        mdCarMenu.setIcon(res.getDotIcon());

        abLaundryMenu.setIcon(res.getOfficeIcon());
        abProgramMenu.setIcon(res.getAppsIcon());
        abUnivMenu.setIcon(res.getOfficeIcon());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        com.alee.laf.tabbedpane.WebTabbedPane webTabbedPane1 = new com.alee.laf.tabbedpane.WebTabbedPane();
        sewaContainerImpl1 = new SewaContainerImpl();
        pengembalianContainerImpl1 = new PengembalianContainerImpl();
        com.dika.view.component.MenuBar menuBar = new com.dika.view.component.MenuBar();
        programMenu = new javax.swing.JMenu();
        changeUsernameMenu = new javax.swing.JMenuItem();
        changePasswordMenu = new javax.swing.JMenuItem();
        javax.swing.JPopupMenu.Separator jSeparator1 = new javax.swing.JPopupMenu.Separator();
        logoutMenu = new javax.swing.JMenuItem();
        exitMenu = new javax.swing.JMenuItem();
        dataManagerMenu = new javax.swing.JMenu();
        mdKaryawanMenu = new javax.swing.JMenuItem();
        mdUserMenu = new javax.swing.JMenuItem();
        javax.swing.JPopupMenu.Separator jSeparator2 = new javax.swing.JPopupMenu.Separator();
        mdCarMenu = new javax.swing.JMenuItem();
        mdMerkMenu = new javax.swing.JMenuItem();
        mdPelangganMenu = new javax.swing.JMenuItem();
        javax.swing.JPopupMenu.Separator jSeparator3 = new javax.swing.JPopupMenu.Separator();
        mdTransaksiMenu = new javax.swing.JMenuItem();
        aboutMenu = new javax.swing.JMenu();
        abProgramMenu = new javax.swing.JMenuItem();
        abLaundryMenu = new javax.swing.JMenuItem();
        abUnivMenu = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Rental Mobil");

        webTabbedPane1.addTab("Penyewaan Mobil", sewaContainerImpl1);
        webTabbedPane1.addTab("Pengembalian Mobil", pengembalianContainerImpl1);

        programMenu.setText("Program");

        changeUsernameMenu.setText("Ganti Username");
        programMenu.add(changeUsernameMenu);

        changePasswordMenu.setText("Ganti Password");
        programMenu.add(changePasswordMenu);
        programMenu.add(jSeparator1);

        logoutMenu.setText("Logout");
        programMenu.add(logoutMenu);

        exitMenu.setText("Keluar");
        programMenu.add(exitMenu);

        menuBar.add(programMenu);

        dataManagerMenu.setText("Data Manager");

        mdKaryawanMenu.setText("Manager Data Karyawan");
        dataManagerMenu.add(mdKaryawanMenu);

        mdUserMenu.setText("Manager Data User");
        dataManagerMenu.add(mdUserMenu);
        dataManagerMenu.add(jSeparator2);

        mdCarMenu.setText("Manager Data Mobil");
        dataManagerMenu.add(mdCarMenu);

        mdMerkMenu.setText("Manager Data Merk");
        dataManagerMenu.add(mdMerkMenu);

        mdPelangganMenu.setText("Manager Data Pelanggan");
        dataManagerMenu.add(mdPelangganMenu);
        dataManagerMenu.add(jSeparator3);

        mdTransaksiMenu.setText("Managaer Data Transaksi");
        dataManagerMenu.add(mdTransaksiMenu);

        menuBar.add(dataManagerMenu);

        aboutMenu.setText("Tentang");

        abProgramMenu.setText("Tentang Program");
        aboutMenu.add(abProgramMenu);

        abLaundryMenu.setText("Tentang Laundry");
        aboutMenu.add(abLaundryMenu);

        abUnivMenu.setText("Tentang Universitas");
        aboutMenu.add(abUnivMenu);

        menuBar.add(aboutMenu);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(webTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 891, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(webTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 547, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem abLaundryMenu;
    private javax.swing.JMenuItem abProgramMenu;
    private javax.swing.JMenuItem abUnivMenu;
    private javax.swing.JMenu aboutMenu;
    private javax.swing.JMenuItem changePasswordMenu;
    private javax.swing.JMenuItem changeUsernameMenu;
    private javax.swing.JMenu dataManagerMenu;
    private javax.swing.JMenuItem exitMenu;
    private javax.swing.JMenuItem logoutMenu;
    private javax.swing.JMenuItem mdCarMenu;
    private javax.swing.JMenuItem mdKaryawanMenu;
    private javax.swing.JMenuItem mdMerkMenu;
    private javax.swing.JMenuItem mdPelangganMenu;
    private javax.swing.JMenuItem mdTransaksiMenu;
    private javax.swing.JMenuItem mdUserMenu;
    private PengembalianContainerImpl pengembalianContainerImpl1;
    private javax.swing.JMenu programMenu;
    private SewaContainerImpl sewaContainerImpl1;
    // End of variables declaration//GEN-END:variables

    @Override
    public JMenu getDataManagerMenu() {
        return dataManagerMenu;
    }

    @Override
    public JMenuItem getAbLaundryMenu() {
        return abLaundryMenu;
    }

    @Override
    public JMenuItem getAbProgramMenu() {
        return abProgramMenu;
    }

    @Override
    public JMenuItem getAbUnivMenu() {
        return abUnivMenu;
    }

    @Override
    public JMenuItem getChangePasswordMenu() {
        return changePasswordMenu;
    }

    @Override
    public JMenuItem getChangeUsernameMenu() {
        return changeUsernameMenu;
    }

    @Override
    public JMenuItem getExitMenu() {
        return exitMenu;
    }

    @Override
    public JMenuItem getLogoutMenu() {
        return logoutMenu;
    }

    @Override
    public JMenuItem getMdKaryawanMenu() {
        return mdKaryawanMenu;
    }

    @Override
    public JMenuItem getMdUserMenu() {
        return mdUserMenu;
    }

    @Override
    public JMenuItem getMdCarMenu() {
        return mdCarMenu;
    }

    @Override
    public JMenuItem getMdPelangganMenu() {
        return mdPelangganMenu;
    }

    @Override
    public JMenuItem getMdMerkMenu() {
        return mdMerkMenu;
    }

    @Override
    public JMenuItem getMdTransaksiMenu() {
        return mdTransaksiMenu;
    }

    @Override
    public SewaContainer getSewaContainer() {
        return sewaContainerImpl1;
    }

    @Override
    public PengembalianContainer getPengembalianContainer() {
        return pengembalianContainerImpl1;
    }

    @Override
    public Frame getRoot() {
        return this;
    }
}
